stages:
    - build
    - test

Buildingding:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/infor.txt
    artifacts:
        paths:
            - build/

tester:
    stage: test
    script: 
        - echo "Testing"
        - test -f "build/info.txt"
